### ISSUE TITLE
Cant load Radegast.Plugin.IRC

### ISSUE THREAD

**Issue by headfim** [radegastdev/radegast#26]
How do one load the irc plugin? Cant find any info about this anywhere.

**Comment by nooperation** [comment]
Currently you will have to checkout the latest code and build the IRC plugin manually. After doing so you'll be able to load Radegast.Plugin.IRC.dll in Radegast. If you've done this and are getting error messages then please post them here along with the operating system you're using

**Comment by nooperation** [comment]
Build script was updated. IRC plugin is now distributed in 1.19beta1.
