### ISSUE TITLE
Dark GTK themes virtualy unusable

### ISSUE THREAD

**Issue by fennectech** [radegastdev/radegast#27]
https://gyazo.com/32819457a7fcd45cfc0c893f51f450a1
Is there a solution for this (other than just use another theme)

**Comment by nooperation** [comment]
I don't know of any viable solutions to this problem asides from the one you mentioned. Radegast uses WinForms to render the interface so GTK themes may not work out of the box with Radegast (or most winform applications in general I assume).

**Comment by fennectech** [comment]
what interface is used to render the dialog menus   as those are perfectly visible and follow the gtk color scheme fine  the issue is present only in the main window  
![d1444b812b1fc07fc55126cd01a194d1](https://cloud.githubusercontent.com/assets/11953665/15987578/1d3bdbe4-2ff2-11e6-880b-656e0b4f3e7a.png)

**Comment by nooperation** [comment]
This appears to be an 8 year old bug that was never fixed in mono dealing with how Toolstrips are rendered. It might be possible to add a setting to use basic toolbar styles in the future so themes are preserved slightly better.

https://bugzilla.novell.com/show_bug.cgi?id=418108

**Comment by fennectech** [comment]
there any way to get that bug updated?     that would be nice    how much work would it be to add such a fix

**Comment by nooperation** [comment]
Do you happen to have a development environment setup so you can checkout and build radegast from source?

If so, try this building this pull request and running it. There should be a 'theme compatibility mode' option in the preferences

**Comment by fennectech** [comment]
i dont   but i would be willing to give it a try if you were to give me some instructions

**Comment by fennectech** [comment]
id be glad to do it   though im unsure how to get the pull request source onto my machine

**Comment by nooperation** [comment]
The following should be all the steps you need to be able to pull and build that pull request, assuming ubuntu/mint or something similar
```
sudo apt-get install mono-devel
sudo apt-get install git

git clone --recursive https://github.com/radegastdev/radegast.git
cd radegast
git checkout -b nooperation-add_theme_compatibility_mode master
git pull https://github.com/nooperation/radegast.git add_theme_compatibility_mode

./runprebuild.sh
xbuild
cd bin
mono Radegast.exe
```

**Comment by fennectech** [comment]
compile suceeded on manjaro   but im unsure where to find the theme compatability mode setting

**Comment by nooperation** [comment]
It should be on the preferences menu, bottom right corner right below 'resolve URIs, Confirm Exit, then Theme compatibility Mode

**Comment by fennectech** [comment]
nope    its not there  :/

On Fri, Jun 17, 2016 at 8:02 PM, nooperation <notifications@github.com>
wrote:

> It should be on the preferences menu, bottom right corner right below
> 'resolve URIs, Confirm Exit, then Theme compatibility Mode
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radegastdev/radegast/issues/27#issuecomment-226912631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZmAdwtAEqKAlI8xBroM4nE8mo911Bjks5qM0OrgaJpZM4Iza5P>
> .
>



-- 
Fennec

**Comment by fennectech** [comment]
8 Warning(s)
         1331 Error(s)
after redoing it (didnt pull the pull request)


does not build

**Comment by nooperation** [comment]
Are you able to build the master branch of radegast? git checkout master then follow the last 4 steps again. if not then could you post the first couple of errors you receive?

**Comment by fennectech** [comment]
no  it doesnt build 
wierd

**Comment by fennectech** [comment]
nevermind    i forgot --recursive when cloning

**Comment by fennectech** [comment]
chat window doenst follow color scheme   but this is tolerable   (would be nice for it to tho xD

**Comment by nooperation** [comment]
Can't really do too much about the main chat window due to all of the custom colors it uses. Maybe later there will be a way to customize the chat colors, but until then this is as good as it gets

**Comment by fennectech** [comment]
where are the colors defined at?    perhaps i could make my own build?

**Comment by nooperation** [comment]
Added color options to settings under the chat tab:
```
git clone --recursive https://github.com/radegastdev/radegast.git
cd radegast
git checkout master
git checkout -b nooperation-adds_color_settings master
git pull https://github.com/nooperation/radegast.git adds_color_settings

./runprebuild.sh
xbuild
cd bin
./Radegast.exe
```

**Comment by fennectech** [comment]
Omg   thank you   your literly the best :D

On Sun, Jun 19, 2016 at 2:30 AM, nooperation <notifications@github.com>
wrote:

> Added color options to settings under the chat tab:
>
> git clone --recursive https://github.com/radegastdev/radegast.git
> cd radegast
> git checkout master
> git checkout -b nooperation-adds_color_settings master
> git pull https://github.com/nooperation/radegast.git adds_color_settings
>
> ./runprebuild.sh
> xbuild
> cd bin
> ./Radegast.exe
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radegastdev/radegast/issues/27#issuecomment-226983821>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZmAfelwyqbiNMGUxp2lfZ2iLnYKJAfks5qNPAEgaJpZM4Iza5P>
> .
>



-- 
Fennec

**Comment by fennectech** [comment]
anything i can do to help get these changes merged into master?

**Comment by nooperation** [comment]
I'll have to test things out a little bit more before i merge it into master, glad to hear it works. A lot of the font functionality can be a bit shoddy with mono's implementation of RichTextBoxs so some features may not work correctly (backcolor for instance)

**Comment by fennectech** [comment]
but its better than having an /actual/ windows install to do this kind of
stuff lol

**Comment by nooperation** [comment]
should be merged into master now :+1:

**Comment by fennectech** [comment]
Cool  awesome    thank you
