### ISSUE TITLE
Radegast uses xorg origional cursor for arrow but nothing else

### ISSUE THREAD

**Issue by fennectech** [radegastdev/radegast#32]
It uses the normal cursor set in mate for the i beam and other click things  but it uses the xorg ugly pointer for some reason   not really proiortiy   but i do find it odd    is there a way i could fix it myself?

**Comment by nooperation** [comment]
I'm not sure about this one. All the other cursors appear to work so I'm assuming mono bug with winforms and themes.

You can try to play around with the Cursor class to create a custom cursor (might need to hit up google/stackoverflow/etc for that one)

**Comment by fennectech** [comment]
oki   thanks ill poke arround in the radegast source see if i can fix it

On Thu, Jun 23, 2016 at 5:58 PM, nooperation <notifications@github.com>
wrote:

> I'm not sure about this one. All the other cursors appear to work so I'm
> assuming mono bug with winforms and themes.
>
> You can try to play around with the Cursor class to create a custom cursor
> (might need to hit up google/stackoverflow/etc for that one)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radegastdev/radegast/issues/32#issuecomment-228210567>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZmATq_TyCnKl4cOA6-PbtYy3QnS8YZks5qOw-TgaJpZM4I5ZL1>
> .
>



-- 
Fennec
