### ISSUE TITLE
RLV/A Needs A Update Please 

### ISSUE THREAD

**Issue by LokiClifton** [radegastdev/radegast#33]
Description

At the current time (July 14 2016) Radegast has a Older version of RLV enabled this older version lacks support for the clothing Outfits folder as defined here http://www.opencollar.at/outfits.html This option allows users to use wear "foldername" as a Command to the Open Collar V6. There are alot of Options that RLV uses but with the older version of RLV in Radegast we cant use this option.

I am working on a project that Uses Radegast ( RLV and AMIL ) on a Bot But I need the support of OpenCollar V6. This should not be a hard update but I NEED IT or my project is Dead.

Steps to Reproduce:

Attach Open Collar V6 Available at (BOULEVARD/50/211/24) for free.
Have RLV enabled
Create a folder in your inventory called #rlv
inside that folder create a folder called .outfits
Add a outfit in a fold with its name to the .outfits folder
Lock Collar from menu
Choice RLV menu from collar
choice outfits from this menu
It will not load the outfits from the .outfits folder

**Comment by SignpostMarv** [comment]
I might not be able to get around to it this evening, but I've located the entry point & RLV manager in Radegast:
* [entry point](../blob/7e2e97b5de2af37fd8734d301c00126325fac5e7/Radegast/Core/ChatTextManager.cs#L299)
* [RLV Manager](../blob/master/Radegast/Core/RLV/RLVManager.cs)

Are there more features for the RLV implementation that need updating?

Task list:
- [ ] Implement Outfits Command as defined in [/outfits.html](http://www.opencollar.at/outfits.html)
- [ ] Write automated tests for RLV features

**Comment by LokiClifton** [comment]
Thank you This Saves my project and I am sure others Given That this RLV in Radagast was not updated in a long time I think there may be more things Wrong with it It is Possible we want to use RLV/a From singularity Source as its fulling working !

**Comment by shyrobbiani** [comment]
Just a note @LokiClifton: while it's certainly sufficient for most Bot related projects, RLV support in Radegast is based on an older protocol and was never complete. Also note that there are more #rlv folder related issues in case you plan to use it on an Opensimulator sim.

@SignpostMarv: I cannot immediately implement the outfit commands but on a longer time frame (e.g. 2 - 6 weeks) I could take a closer look over the current rlv protocol implementation and provide updates where it's possible and needed.

**Comment by LokiClifton** [comment]
@shyrobbiani  I thank you for that I know Opensim Is a Whole New issue but for right now SL is where my projects live. as my project grows I know I will find my needs and Scope of needs changing However for right now the Outfits usage is the only thing ATM that is holding up my projects.

**Comment by SignpostMarv** [comment]
@shyrobbiani poking around the code, noticing that FindFolderInternal blocks access to folders starting with ".", so I'm guessing this would need a tweak for the .outfits folder, then presumably a "get all wearables in this folder & sub-folders and wear them all" call

**Comment by LokiClifton** [comment]
If it helps https://github.com/singularity-viewer/SingularityViewer.git Has a Working Version of the .outfits

**Comment by LokiClifton** [comment]
@SignpostMarv, Do you need me to help Test? also if its possible can this update be made to a mac version as well? (Not a priority)

**Comment by SignpostMarv** [comment]
@LokiClifton that'd be handy, send me an in-world IM when you're free.

**Comment by SignpostMarv** [comment]
@shyrobbiani I've managed to get Radegast to spit out a list of folder names to OpenCollar, although I'm averse to reading through the singu source code due to license (gpl)/having-to-read-c++ issues

If one manually calls the methods as follows, it works, so presumably Radegast is failing to send a sufficient response to allow OpenCollar to send the `@attach` command back:
```
@remoutfit=force,detach=force
@attach:.outfits/foo/=force
```

**Comment by nooperation** [comment]
Getting outfits to work isn't too bad, but unfortunately the no-detach ability (lock/unlock in the open collar interface) is not implemented in radegast, which means that object will be removed when switching outfits and things will break

**Comment by nooperation** [comment]
Also, the way that a lot of viewers seem to handle "private" directories (starting with a period '.') is that the only thing private about them is that they're not listed in the output. They can still be a target.

E.g.
```
root
 |
 |- .hidden
 |       |- Public1
 |       \- .Private1
 |              | - Public2
 |              | - Public3
 |              \- .Private2
 \ - Public4
          \- Public5

@getinv:.hidden/           --> Public1
@getinv:.hidden/.Private1/ --> Public2,Public3
@getinv:Public4/           --> Public3
@findfolder:Public3        --> .hidden/.Private1/Public3
```

**Comment by nooperation** [comment]
@LokiClifton Are you able to compile Radegast? Could you try checking out this pull request to see if it resolves the issue https://github.com/radegastdev/radegast/pull/34

**Comment by LokiClifton** [comment]
I am not able to compile as I am on a mac as my my system but if I can figuerout how to get to source I can Try.

**Comment by LokiClifton** [comment]
So what happens now ?

**Comment by nooperation** [comment]
I'd prefer it if you could build the codebase yourself, but I don't have any guides or machines running mac to be able to walk you through it unfortunately. Below are just the compiled binaries from that branch that have the change, but I'm uncertain if they'll run on your system. Contained in the archive are just the modified files so you'll need to overwrite the files of a full installation of radegast with these. Backup your previous copy of radegast so you're able to restore it.

[rlv_oc_outfit_support.zip](https://github.com/radegastdev/radegast/files/379255/rlv_oc_outfit_support.zip)

**Comment by LokiClifton** [comment]
I will take it for PC dont care as long as it works

**Comment by LokiClifton** [comment]
Tested 
will not populate The contents of Outfits returnes - - back as only 3 options 
and Folders returns nothing no menu or anything

**Comment by LokiClifton** [comment]
Bug: Once an outfit is worn - it will no longer change again until menu is brought back up.  BACK does go back - but nothing works and when you touch it it goes away.  Only solution is to type 'av initials' menu to get it to reopen.  After this happen when it reopens occasionally when you go to outfits and select one a blank box come up (after outfit choice is made) and you must close it - not use back button, because under it is the 'real' outfit menu with an active 'wear' button.  It works - but then every time you bring it up has faux blank menu box on top.  .root menu seems to work fine and keeps those items in place.  After the faux menu box has come up a few times outfits will no longer change (as though the process is now damaged).

So: 

1) Why does menu not return to previous men so additional outfits can be tried on?
2) Why does the faux blank menu box come up in front of actual menu box?  
3. Why does outfits folder (which does show outfits) stop working altogether after a few faux boxes have appeared and be removed (ignore button)?

**Comment by LokiClifton** [comment]
So all works but the Chat command to Wear FOLDERNAME as defined http://www.opencollar.at/outfits.html 

# wear "foldername"
	
wears the outfit named

**Comment by nooperation** [comment]
They appear to be using an undocumented "findfolders" command. Is there an official documentation for RLV commands? It's not found in http://wiki.secondlife.com/wiki/LSL_Protocol/RestrainedLoveAPI but I do see firestorm supports that command

**Comment by LokiClifton** [comment]
RLV Creater http://wiki.secondlife.com/wiki/LSL_Protocol/RestrainedLoveAPI is current

**Comment by nooperation** [comment]
Added addfolders support https://github.com/nooperation/radegast/releases/tag/build-34-rlv_addfolders_support-2016-07-24

**Comment by LokiClifton** [comment]
This works But one tiny big is you cant change Text Size at all for text

**Comment by LokiClifton** [comment]
also some issues with AIML AI system integration

**Comment by shyrobbiani** [comment]
What are your issues with AIML integration?

**Comment by LokiClifton** [comment]
After testing looks to be working correctly now Thank you
